### ISSUE TITLE
hello guy, thanks for the dart 3d game engine

### ISSUE THREAD

**Issue by chenxyzl** [pjako/harmony3d#1]
this is somethings i can not find.
could you help me?
dependencies:
  aabb_tree:
    path: /Users/jako/projects_dart/aabb_tree
  animator:
    path: /Users/jako/projects_dart/animator
  dml:
    path: /Users/jako/projects/dart_ml
  harmony3d_terrain:
    path: /Users/jako/projects_dart/harmony3d_terrain
  harmony_devices:
    path: /Users/jako/projects_dart/harmony_devices
  mist:
    path: ../../dart/mist

**Comment by pjako** [comment]
Hello,
I have not developed on this engine since my bachelor thesis. These dependencies should point towards one of my git repositories.
I think "harmony3d_terrain" can be removed.
"mist" not sure if compile transforms still work like two years ago.

If you like you can create a pull request with a fix.

**Comment by chenxyzl** [comment]
thanks for your reply,
